# Generated by Django 4.1.1 on 2022-09-14 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Portals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_id', models.CharField(max_length=255, unique=True, verbose_name='Уникальный код портала')),
                ('name', models.CharField(max_length=255, verbose_name='Имя портала')),
                ('auth_id', models.CharField(max_length=255, verbose_name='Токен аутентификации')),
                ('auth_id_create_date', models.DateTimeField(auto_now=True, verbose_name='Дата получения токена аутентификации')),
                ('refresh_id', models.CharField(max_length=255, verbose_name='Токен обновления')),
                ('client_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='Уникальный ID клиента')),
                ('client_secret', models.CharField(blank=True, max_length=100, null=True, verbose_name='Секретный токен клиента')),
            ],
            options={
                'verbose_name': 'Портал',
                'verbose_name_plural': 'Порталы',
            },
        ),
    ]
