# Generated by Django 4.1.1 on 2022-09-14 05:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SettingsPortal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.portals', verbose_name='Портал')),
            ],
            options={
                'verbose_name': 'Настройка портала',
                'verbose_name_plural': 'Настройки портала',
                'ordering': ['portal', 'pk'],
            },
        ),
    ]
